// FENIX Project Manager - Test Orchestrator
// Test script for Agent Orchestrator
// Created: January 6, 2026

import { createAgentOrchestrator } from '../services/AgentOrchestrator';
import type { Workflow } from '../models/orchestration-types';
// import type { WorkflowStep } from '../models/orchestration-types'; // Reserved for future use

/**
 * Test basic workflow execution
 */
async function testBasicWorkflow() {
  console.log('\n🧪 Testing Basic Workflow...\n');

  const orchestrator = createAgentOrchestrator();

  // Create a simple 2-step workflow
  const workflow: Workflow = {
    id: 'test-workflow-1',
    name: 'Simple Test Workflow',
    description: 'Test PowerPoint and Excel generation',
    steps: [
      {
        id: 'step-1',
        name: 'Generate PowerPoint',
        agent: 'powerpoint',
        task: 'generate',
        inputs: {
          title: 'Test Presentation',
          slides: [
            {
              type: 'title',
              title: 'Test Presentation',
              subtitle: 'Generated by Orchestrator'
            }
          ]
        },
        status: 'pending',
        dependencies: []
      },
      {
        id: 'step-2',
        name: 'Generate Excel',
        agent: 'excel',
        task: 'generate',
        inputs: {
          title: 'Test Workbook',
          sheets: [
            {
              name: 'Data',
              data: [[1, 2, 3], [4, 5, 6]]
            }
          ]
        },
        status: 'pending',
        dependencies: []
      }
    ],
    dependencies: [],
    status: 'pending',
    createdAt: new Date()
  };

  try {
    console.log('📋 Workflow:', workflow.name);
    console.log('📝 Steps:', workflow.steps.length);
    console.log('⚙️  Execution mode: parallel\n');

    const result = await orchestrator.executeWorkflow(workflow, {
      executionMode: 'parallel'
    });

    console.log('✅ Workflow completed successfully!');
    console.log('⏱️  Duration:', result.duration, 'ms');
    console.log('📊 Steps completed:', result.steps.length);
    console.log('📁 Outputs:', Object.keys(result.outputs).length, 'items\n');

    return true;
  } catch (error) {
    console.error('❌ Workflow failed:', error);
    return false;
  }
}

/**
 * Test sequential workflow
 */
async function testSequentialWorkflow() {
  console.log('\n🧪 Testing Sequential Workflow...\n');

  const orchestrator = createAgentOrchestrator();

  // Create workflow with dependencies
  const workflow: Workflow = {
    id: 'test-workflow-2',
    name: 'Sequential Test Workflow',
    description: 'Test sequential execution with dependencies',
    steps: [
      {
        id: 'step-1',
        name: 'Generate PowerPoint',
        agent: 'powerpoint',
        task: 'generate',
        inputs: {
          title: 'Project Status',
          slides: [
            {
              type: 'title',
              title: 'Project Status',
              subtitle: 'Q1 2026'
            }
          ]
        },
        status: 'pending',
        dependencies: []
      },
      {
        id: 'step-2',
        name: 'Generate Summary',
        agent: 'word',
        task: 'generate',
        inputs: {
          title: 'Executive Summary',
          content: 'Summary based on presentation'
        },
        status: 'pending',
        dependencies: ['step-1'] // Depends on step-1
      }
    ],
    dependencies: [
      {
        fromStep: 'step-1',
        toStep: 'step-2',
        dataMapping: {
          content: 'presentation.summary'
        }
      }
    ],
    status: 'pending',
    createdAt: new Date()
  };

  try {
    console.log('📋 Workflow:', workflow.name);
    console.log('📝 Steps:', workflow.steps.length);
    console.log('🔗 Dependencies:', workflow.dependencies.length);
    console.log('⚙️  Execution mode: mixed\n');

    const result = await orchestrator.executeWorkflow(workflow, {
      executionMode: 'mixed'
    });

    console.log('✅ Workflow completed successfully!');
    console.log('⏱️  Duration:', result.duration, 'ms');
    console.log('📊 Steps completed:', result.steps.length);
    console.log('📁 Outputs:', Object.keys(result.outputs).length, 'items\n');

    return true;
  } catch (error) {
    console.error('❌ Workflow failed:', error);
    return false;
  }
}

/**
 * Test orchestrator status
 */
function testOrchestratorStatus() {
  console.log('\n🧪 Testing Orchestrator Status...\n');

  const orchestrator = createAgentOrchestrator();
  const status = orchestrator.getStatus();

  console.log('📊 Orchestrator Status:');
  console.log('  Active workflows:', status.activeWorkflows);
  console.log('  Completed workflows:', status.completedWorkflows);
  console.log('  Failed workflows:', status.failedWorkflows);
  console.log('  Uptime:', status.uptime, 'ms');
  console.log('\n🤖 Agent Status:');
  status.agents.forEach(agent => {
    console.log(`  ${agent.agent}:`, agent.available ? '✅ Available' : '⏳ Busy');
  });
  console.log();

  return true;
}

/**
 * Main test runner
 */
async function main() {
  console.log('╔════════════════════════════════════════╗');
  console.log('║  FENIX Agent Orchestrator Test Suite  ║');
  console.log('╚════════════════════════════════════════╝');

  const tests = [
    { name: 'Orchestrator Status', fn: testOrchestratorStatus },
    { name: 'Basic Workflow', fn: testBasicWorkflow },
    { name: 'Sequential Workflow', fn: testSequentialWorkflow }
  ];

  let passed = 0;
  let failed = 0;

  for (const test of tests) {
    try {
      const result = await test.fn();
      if (result) {
        passed++;
        console.log(`✅ ${test.name} - PASSED\n`);
      } else {
        failed++;
        console.log(`❌ ${test.name} - FAILED\n`);
      }
    } catch (error) {
      failed++;
      console.log(`❌ ${test.name} - ERROR:`, error, '\n');
    }
  }

  console.log('╔════════════════════════════════════════╗');
  console.log('║           Test Results                 ║');
  console.log('╚════════════════════════════════════════╝');
  console.log(`✅ Passed: ${passed}`);
  console.log(`❌ Failed: ${failed}`);
  console.log(`📊 Total: ${tests.length}\n`);

  process.exit(failed > 0 ? 1 : 0);
}

// Run tests
main().catch(console.error);
